package de.greenrobot.daogenerator.Schema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daogenerator.Schema.Food;
import de.greenrobot.daogenerator.Schema.FoodType;
import de.greenrobot.daogenerator.Schema.Episode;
import de.greenrobot.daogenerator.Schema.FoodsEpisode;

import de.greenrobot.daogenerator.Schema.FoodDao;
import de.greenrobot.daogenerator.Schema.FoodTypeDao;
import de.greenrobot.daogenerator.Schema.EpisodeDao;
import de.greenrobot.daogenerator.Schema.FoodsEpisodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodDaoConfig;
    private final DaoConfig foodTypeDaoConfig;
    private final DaoConfig episodeDaoConfig;
    private final DaoConfig foodsEpisodeDaoConfig;

    private final FoodDao foodDao;
    private final FoodTypeDao foodTypeDao;
    private final EpisodeDao episodeDao;
    private final FoodsEpisodeDao foodsEpisodeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        foodTypeDaoConfig = daoConfigMap.get(FoodTypeDao.class).clone();
        foodTypeDaoConfig.initIdentityScope(type);

        episodeDaoConfig = daoConfigMap.get(EpisodeDao.class).clone();
        episodeDaoConfig.initIdentityScope(type);

        foodsEpisodeDaoConfig = daoConfigMap.get(FoodsEpisodeDao.class).clone();
        foodsEpisodeDaoConfig.initIdentityScope(type);

        foodDao = new FoodDao(foodDaoConfig, this);
        foodTypeDao = new FoodTypeDao(foodTypeDaoConfig, this);
        episodeDao = new EpisodeDao(episodeDaoConfig, this);
        foodsEpisodeDao = new FoodsEpisodeDao(foodsEpisodeDaoConfig, this);

        registerDao(Food.class, foodDao);
        registerDao(FoodType.class, foodTypeDao);
        registerDao(Episode.class, episodeDao);
        registerDao(FoodsEpisode.class, foodsEpisodeDao);
    }
    
    public void clear() {
        foodDaoConfig.getIdentityScope().clear();
        foodTypeDaoConfig.getIdentityScope().clear();
        episodeDaoConfig.getIdentityScope().clear();
        foodsEpisodeDaoConfig.getIdentityScope().clear();
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public FoodTypeDao getFoodTypeDao() {
        return foodTypeDao;
    }

    public EpisodeDao getEpisodeDao() {
        return episodeDao;
    }

    public FoodsEpisodeDao getFoodsEpisodeDao() {
        return foodsEpisodeDao;
    }

}
