package de.greenrobot.daogenerator.Schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EPISODE".
 */
public class Episode {

    private Long id;
    private String name;

    public Episode() {
    }

    public Episode(Long id) {
        this.id = id;
    }

    public Episode(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
