package de.greenrobot.daogenerator.Schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FOOD_TYPE".
 */
public class FoodType {

    private Long FoodTypeId;
    /** Not-null value. */
    private String name;

    public FoodType() {
    }

    public FoodType(Long FoodTypeId) {
        this.FoodTypeId = FoodTypeId;
    }

    public FoodType(Long FoodTypeId, String name) {
        this.FoodTypeId = FoodTypeId;
        this.name = name;
    }

    public Long getFoodTypeId() {
        return FoodTypeId;
    }

    public void setFoodTypeId(Long FoodTypeId) {
        this.FoodTypeId = FoodTypeId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
