package de.greenrobot.daogenerator.Schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FOOD".
 */
public class Food {

    private Long id;
    private Integer typeId;
    /** Not-null value. */
    private String name;

    public Food() {
    }

    public Food(Long id) {
        this.id = id;
    }

    public Food(Long id, Integer typeId, String name) {
        this.id = id;
        this.typeId = typeId;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
