package de.greenrobot.daogenerator.Schema;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daogenerator.Schema.FoodType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOOD_TYPE".
*/
public class FoodTypeDao extends AbstractDao<FoodType, Long> {

    public static final String TABLENAME = "FOOD_TYPE";

    /**
     * Properties of entity FoodType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FoodTypeId = new Property(0, Long.class, "FoodTypeId", true, "FOOD_TYPE_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    };


    public FoodTypeDao(DaoConfig config) {
        super(config);
    }
    
    public FoodTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOOD_TYPE\" (" + //
                "\"FOOD_TYPE_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: FoodTypeId
                "\"NAME\" TEXT NOT NULL );"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOOD_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FoodType entity) {
        stmt.clearBindings();
 
        Long FoodTypeId = entity.getFoodTypeId();
        if (FoodTypeId != null) {
            stmt.bindLong(1, FoodTypeId);
        }
        stmt.bindString(2, entity.getName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FoodType readEntity(Cursor cursor, int offset) {
        FoodType entity = new FoodType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // FoodTypeId
            cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FoodType entity, int offset) {
        entity.setFoodTypeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FoodType entity, long rowId) {
        entity.setFoodTypeId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FoodType entity) {
        if(entity != null) {
            return entity.getFoodTypeId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
