package www.example.com.greendao.modle;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import www.example.com.greendao.modle.Food;
import www.example.com.greendao.modle.FoodType;

import www.example.com.greendao.modle.FoodDao;
import www.example.com.greendao.modle.FoodTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodDaoConfig;
    private final DaoConfig foodTypeDaoConfig;

    private final FoodDao foodDao;
    private final FoodTypeDao foodTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        foodTypeDaoConfig = daoConfigMap.get(FoodTypeDao.class).clone();
        foodTypeDaoConfig.initIdentityScope(type);

        foodDao = new FoodDao(foodDaoConfig, this);
        foodTypeDao = new FoodTypeDao(foodTypeDaoConfig, this);

        registerDao(Food.class, foodDao);
        registerDao(FoodType.class, foodTypeDao);
    }
    
    public void clear() {
        foodDaoConfig.getIdentityScope().clear();
        foodTypeDaoConfig.getIdentityScope().clear();
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public FoodTypeDao getFoodTypeDao() {
        return foodTypeDao;
    }

}
